---
          - name: restart named-chroot
            service:
                    name: named-chroot
                    state: restarted

          - name: reload NetworkManager
            service:
                    name: NetworkManager
                    state: reloaded

                

                    

                    





