---
# tasks file for prod_nfs_mounts


 - name: create the mount point /nsfshare
   file:
     path: /nfsshare
     state: directory
     owner: root
     mode: 0777



 - name: install nfs-utils package
   package:
     name: nfs-utils
     state: present


 - name: install nfs4-acl-tools package
   package:
     name: nfs4-acl-tools
     state: present



 - name: Ensure nfs share  /nfsshare is not mounted twice
   lineinfile:
     path: /etc/fstab
     regexp: /nfsshare
     state: absent


 - name: mount common nfs share  /nfsshare
   mount:
     path: /nfsshare
     src: 10.0.5.18:/nfsshare
     fstype: nfs4
     opts: _netdev,rw,sync,defaults
     state: mounted
